runtime: python
env: flex


instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

service: default

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /https://storage.googleapis.com/welm/static
  static_dir: /static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto